package resource

import "github.com/aws-cloudformation/cloudformation-cli-go-plugin/cfn/encoding"

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	UID   *encoding.String `json:"UID,omitempty"`
	Name  *encoding.String `json:"Name,omitempty"`
	Age   *encoding.Float  `json:"Age,omitempty"`
	Color *encoding.String `json:"Color,omitempty"`
}
